name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/portfolio

          git pull origin main

          docker build -t portfolio-site .

          docker rm -f portfolio || true

          docker run -d \
            --restart unless-stopped \
            --name portfolio \
            -p 8080:80 \
            portfolio-site

          sudo systemctl restart nginx